general.import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 20
[[keyboard.bindings]]
key = "Escape"
mods = "Control"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "V"
mods = "None"
mode = "Vi"
action = "ToggleNormalSelection"
